name:                claims-x12-dsl
version:             0.1.0.0
github:              "githubuser/claims-x12-dsl"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2026 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/claims-x12-dsl#readme>

dependencies:
- base >= 4.7 && < 5
- text >= 1.2 && < 2.2
- time >= 1.9 && < 1.15
- Decimal >= 0.5 && < 0.6
- parsec >= 3.1 && < 3.2
- containers >= 0.6 && < 0.8

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  claims-x12-dsl-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - claims-x12-dsl

tests:
  claims-x12-dsl-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - claims-x12-dsl
    - hspec >= 2.7 && < 2.12
    - QuickCheck >= 2.14 && < 2.16
